name: Juliano Mohr
markdown: kramdown
url: https://www.juliaaano.com
permalink: /blog/:year/:month/:day/:title/

source: source

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

excerpt_separator: <!--more-->

# https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: "/page/:num/"

# https://github.com/jekyll/jekyll-feed
# feed:
#   title: juliaaano.com
#   subtitle: Programming Blog

# https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: juliaaano
  card: summary

author:
  name: Juliano Mohr
  twitter: juliaaano

social:
  name: Juliano Mohr
  links:
    - https://twitter.com/juliaaano
    - https://www.linkedin.com/in/juliaaano
    - https://github.com/juliaaano

defaults:
  - scope:
      path: ""
    values:
      image: https://d27nechif2d87h.cloudfront.net/images/juliano-bonanza-coffee.jpg

# https://github.com/penibelst/jekyll-compress-html
compress_html:
  ignore:
    envs: [development]

cdn:
  http: "http://cdn.juliaaano.com"
  https: "https://d27nechif2d87h.cloudfront.net"
